/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    subcategories: Subcategory;
    products: Product;
    bundles: Bundle;
    orders: Order;
    posts: Post;
    'hero-slides': HeroSlide;
    'contact-submissions': ContactSubmission;
    'newsletter-subscribers': NewsletterSubscriber;
    'email-campaigns': EmailCampaign;
    checkouts: Checkout;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    subcategories: SubcategoriesSelect<false> | SubcategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    bundles: BundlesSelect<false> | BundlesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'hero-slides': HeroSlidesSelect<false> | HeroSlidesSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'newsletter-subscribers': NewsletterSubscribersSelect<false> | NewsletterSubscribersSelect<true>;
    'email-campaigns': EmailCampaignsSelect<false> | EmailCampaignsSelect<true>;
    checkouts: CheckoutsSelect<false> | CheckoutsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * User's full name
   */
  name?: string | null;
  /**
   * User role - determines access permissions
   */
  role: 'admin' | 'customer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Main product categories for the storefront
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * Category name (e.g., Academic & Bio-Med)
   */
  title: string;
  /**
   * URL-friendly identifier (auto-generated from title)
   */
  slug: string;
  /**
   * Brief description of the category
   */
  description?: string | null;
  /**
   * Category image for storefront display
   */
  image?: (number | null) | Media;
  /**
   * Icon to display for this category
   */
  icon?: ('Microscope' | 'ChartLine' | 'Sparkles' | 'Palette' | 'Workflow' | 'Folder') | null;
  /**
   * Gradient color for category card background
   */
  gradient?:
    | (
        | 'from-blue-500 to-cyan-500'
        | 'from-emerald-500 to-green-500'
        | 'from-purple-500 to-pink-500'
        | 'from-orange-500 to-red-500'
        | 'from-indigo-500 to-violet-500'
        | 'from-gray-500 to-gray-600'
      )
    | null;
  status: 'active' | 'archived';
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Product subcategories (products are assigned to these)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subcategories".
 */
export interface Subcategory {
  id: number;
  /**
   * Subcategory name (e.g., Study Planners, Budget Templates)
   */
  title: string;
  /**
   * URL-friendly identifier (auto-generated from title)
   */
  slug: string;
  /**
   * Brief description of the subcategory
   */
  description?: string | null;
  /**
   * Parent category this subcategory belongs to
   */
  category: number | Category;
  status: 'active' | 'archived';
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * URL-friendly identifier (auto-generated from title)
   */
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Brief description for listings
   */
  shortDescription?: string | null;
  /**
   * Product subcategory (determines the parent category)
   */
  subcategory: number | Subcategory;
  /**
   * Product creator - auto-set to current user
   */
  createdBy: number | User;
  /**
   * Polar.sh product ID - one per price point
   */
  polarProductId: string;
  /**
   * Price in cents (e.g., 999 = $9.99). Must match Polar price.
   */
  price: number;
  /**
   * Original price in cents for sale display (optional)
   */
  compareAtPrice?: number | null;
  /**
   * Downloadable product file (PDF, ZIP, etc.)
   */
  file: number | Media;
  images?:
    | {
        image: number | Media;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  status: 'active' | 'draft' | 'archived';
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bundles".
 */
export interface Bundle {
  id: number;
  title: string;
  /**
   * URL-friendly identifier (auto-generated from title)
   */
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Brief description for listings
   */
  shortDescription?: string | null;
  /**
   * Polar.sh product ID - one bundle = one Polar product
   */
  polarProductId: string;
  /**
   * Bundle price in cents (e.g., 2999 = $29.99). Must match Polar price.
   */
  price: number;
  /**
   * Original price in cents (sum of individual products) for savings display
   */
  compareAtPrice?: number | null;
  /**
   * Products included in this bundle
   */
  products: (number | Product)[];
  heroImage?: (number | null) | Media;
  /**
   * Bundle creator - auto-set to current user
   */
  createdBy: number | User;
  status: 'active' | 'draft' | 'archived';
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Orders are created automatically when customers complete checkout. Do not create manually.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * Polar.sh order ID
   */
  polarOrderId: string;
  /**
   * Polar.sh checkout ID
   */
  polarCheckoutId?: string | null;
  /**
   * Customer email
   */
  email: string;
  /**
   * Payload user (null for guest checkout)
   */
  user?: (number | null) | User;
  status: 'pending' | 'completed' | 'failed' | 'refunded';
  items: {
    type: 'product' | 'bundle';
    productId?: (number | null) | Product;
    bundleId?: (number | null) | Bundle;
    /**
     * Product/bundle title at time of purchase
     */
    title: string;
    /**
     * R2 file key for download
     */
    fileKey: string;
    maxDownloads: number;
    downloadsUsed: number;
    id?: string | null;
  }[];
  /**
   * Order expiration date (null = never expires)
   */
  expiresAt?: string | null;
  /**
   * Total amount in cents
   */
  totalAmount: number;
  currency: string;
  /**
   * Whether fulfillment emails have been sent
   */
  fulfilled?: boolean | null;
  /**
   * Whether upsell email has been sent
   */
  upsellSent?: boolean | null;
  /**
   * Product creator who gets revenue attribution
   */
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * URL-friendly identifier (auto-generated from title)
   */
  slug: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Brief excerpt for listings
   */
  excerpt?: string | null;
  featuredImage?: (number | null) | Media;
  /**
   * Post category
   */
  category?: (number | null) | Category;
  /**
   * Post author - auto-set to current user
   */
  createdBy: number | User;
  status: 'published' | 'draft' | 'archived';
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage homepage hero carousel slides
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-slides".
 */
export interface HeroSlide {
  id: number;
  /**
   * Internal title for this slide
   */
  title: string;
  /**
   * Main headline text displayed on the slide
   */
  headline: string;
  /**
   * Supporting text below the headline
   */
  subheadline?: string | null;
  /**
   * Background image for the slide (recommended: 1920x800)
   */
  image: number | Media;
  /**
   * Optional mobile-optimized image (recommended: 800x1200)
   */
  mobileImage?: (number | null) | Media;
  /**
   * Primary call-to-action button
   */
  primaryCta: {
    label: string;
    href: string;
  };
  /**
   * Optional secondary call-to-action button
   */
  secondaryCta?: {
    label?: string | null;
    href?: string | null;
  };
  /**
   * Position of the text content on the slide
   */
  textPosition?: ('left' | 'center' | 'right') | null;
  /**
   * Text color scheme
   */
  textColor?: ('light' | 'dark') | null;
  /**
   * Dark overlay opacity for better text readability
   */
  overlayOpacity?: ('0' | '20' | '40' | '60') | null;
  /**
   * Display order (lower numbers appear first)
   */
  order: number;
  status: 'active' | 'draft' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * Contact form submissions from website visitors
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  /**
   * Optional phone number
   */
  phone?: string | null;
  subject: string;
  message: string;
  status: 'new' | 'in-progress' | 'resolved' | 'spam';
  /**
   * Internal notes about this submission
   */
  notes?: string | null;
  /**
   * Team member handling this inquiry
   */
  assignedTo?: (number | null) | User;
  /**
   * Page or form where submission originated
   */
  source?: string | null;
  /**
   * IP address of submitter (for spam prevention)
   */
  ipAddress?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Newsletter subscription list
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers".
 */
export interface NewsletterSubscriber {
  id: number;
  email: string;
  /**
   * Optional first name for personalization
   */
  firstName?: string | null;
  status: 'subscribed' | 'unsubscribed' | 'bounced' | 'complained';
  /**
   * Where the subscriber signed up
   */
  source?: ('footer' | 'popup' | 'checkout' | 'blog' | 'landing' | 'import' | 'other') | null;
  /**
   * Topics the subscriber is interested in
   */
  interests?:
    | (
        | 'academic-bio-med'
        | 'wealth-finance'
        | 'life-legacy'
        | 'digital-aesthetic'
        | 'work-flow'
        | 'new-products'
        | 'sales'
      )[]
    | null;
  /**
   * When the user first subscribed
   */
  subscribedAt?: string | null;
  /**
   * When the user unsubscribed (if applicable)
   */
  unsubscribedAt?: string | null;
  /**
   * IP address at time of subscription
   */
  ipAddress?: string | null;
  /**
   * Browser/device info at time of subscription
   */
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Email marketing campaigns
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-campaigns".
 */
export interface EmailCampaign {
  id: number;
  /**
   * Internal name for this campaign
   */
  name: string;
  type: 'new-product' | 'upsell' | 'newsletter' | 'promotion' | 'cart-abandonment' | 're-engagement';
  status: 'draft' | 'scheduled' | 'sending' | 'sent' | 'failed';
  /**
   * Email subject line
   */
  subject: string;
  /**
   * Preview text shown in email clients (optional)
   */
  previewText?: string | null;
  /**
   * Email body content
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Call-to-action button text (e.g., 'Shop Now')
   */
  ctaText?: string | null;
  /**
   * Call-to-action button URL
   */
  ctaUrl?: string | null;
  audience: 'all-subscribers' | 'recent-customers' | 'all-customers' | 'by-interest' | 'custom';
  /**
   * Target subscribers with these interests
   */
  interests?:
    | (
        | 'academic-bio-med'
        | 'wealth-finance'
        | 'life-legacy'
        | 'digital-aesthetic'
        | 'work-flow'
        | 'new-products'
        | 'sales'
      )[]
    | null;
  /**
   * Enter email addresses, one per line
   */
  customEmails?: string | null;
  /**
   * Exclude customers who already purchased the promoted product
   */
  excludePurchasers?: boolean | null;
  /**
   * Link to a specific product (for new product announcements)
   */
  linkedProduct?: (number | null) | Product;
  /**
   * Link to a specific bundle
   */
  linkedBundle?: (number | null) | Bundle;
  /**
   * Number of recipients
   */
  recipientCount?: number | null;
  /**
   * When the campaign was sent
   */
  sentAt?: string | null;
  /**
   * Schedule send time (optional)
   */
  scheduledFor?: string | null;
  errorMessage?: string | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Checkout sessions for cart abandonment tracking
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "checkouts".
 */
export interface Checkout {
  id: number;
  /**
   * Polar.sh checkout ID
   */
  polarCheckoutId: string;
  /**
   * Customer email (if provided)
   */
  email?: string | null;
  items?:
    | {
        type: 'product' | 'bundle';
        productId?: number | null;
        title: string;
        /**
         * Price in cents
         */
        price?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Total amount in cents
   */
  totalAmount?: number | null;
  /**
   * Whether checkout was completed
   */
  completed?: boolean | null;
  /**
   * Whether abandonment email was sent
   */
  abandonmentEmailSent?: boolean | null;
  /**
   * Polar checkout URL for retry
   */
  checkoutUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'subcategories';
        value: number | Subcategory;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'bundles';
        value: number | Bundle;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'hero-slides';
        value: number | HeroSlide;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'newsletter-subscribers';
        value: number | NewsletterSubscriber;
      } | null)
    | ({
        relationTo: 'email-campaigns';
        value: number | EmailCampaign;
      } | null)
    | ({
        relationTo: 'checkouts';
        value: number | Checkout;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  image?: T;
  icon?: T;
  gradient?: T;
  status?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subcategories_select".
 */
export interface SubcategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  category?: T;
  status?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  shortDescription?: T;
  subcategory?: T;
  createdBy?: T;
  polarProductId?: T;
  price?: T;
  compareAtPrice?: T;
  file?: T;
  images?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  status?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bundles_select".
 */
export interface BundlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  shortDescription?: T;
  polarProductId?: T;
  price?: T;
  compareAtPrice?: T;
  products?: T;
  heroImage?: T;
  createdBy?: T;
  status?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  polarOrderId?: T;
  polarCheckoutId?: T;
  email?: T;
  user?: T;
  status?: T;
  items?:
    | T
    | {
        type?: T;
        productId?: T;
        bundleId?: T;
        title?: T;
        fileKey?: T;
        maxDownloads?: T;
        downloadsUsed?: T;
        id?: T;
      };
  expiresAt?: T;
  totalAmount?: T;
  currency?: T;
  fulfilled?: T;
  upsellSent?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  excerpt?: T;
  featuredImage?: T;
  category?: T;
  createdBy?: T;
  status?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-slides_select".
 */
export interface HeroSlidesSelect<T extends boolean = true> {
  title?: T;
  headline?: T;
  subheadline?: T;
  image?: T;
  mobileImage?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  textPosition?: T;
  textColor?: T;
  overlayOpacity?: T;
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  subject?: T;
  message?: T;
  status?: T;
  notes?: T;
  assignedTo?: T;
  source?: T;
  ipAddress?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers_select".
 */
export interface NewsletterSubscribersSelect<T extends boolean = true> {
  email?: T;
  firstName?: T;
  status?: T;
  source?: T;
  interests?: T;
  subscribedAt?: T;
  unsubscribedAt?: T;
  ipAddress?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-campaigns_select".
 */
export interface EmailCampaignsSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  status?: T;
  subject?: T;
  previewText?: T;
  content?: T;
  ctaText?: T;
  ctaUrl?: T;
  audience?: T;
  interests?: T;
  customEmails?: T;
  excludePurchasers?: T;
  linkedProduct?: T;
  linkedBundle?: T;
  recipientCount?: T;
  sentAt?: T;
  scheduledFor?: T;
  errorMessage?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "checkouts_select".
 */
export interface CheckoutsSelect<T extends boolean = true> {
  polarCheckoutId?: T;
  email?: T;
  items?:
    | T
    | {
        type?: T;
        productId?: T;
        title?: T;
        price?: T;
        id?: T;
      };
  totalAmount?: T;
  completed?: T;
  abandonmentEmailSent?: T;
  checkoutUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}