/**
 * Lemon Squeezy Checkout Integration
 * 
 * This module provides functions for generating checkout URLs and opening
 * the Lemon Squeezy checkout overlay for direct product purchases.
 */

/**
 * Configuration for checkout URL generation
 */
interface CheckoutConfig {
  productId: string;
  variantId?: string;
  customData?: Record<string, string | number>;
  discountCode?: string;
}

/**
 * Generate a Lemon Squeezy checkout URL with product and redirect configuration
 * 
 * @param config - Checkout configuration including product ID and optional variant
 * @returns Complete checkout URL ready to be used in overlay or direct navigation
 * @throws Error if productId is missing or invalid
 * 
 * @example
 * ```typescript
 * const checkoutUrl = generateCheckoutUrl({
 *   productId: '123456',
 *   variantId: '789012'
 * });
 * ```
 */
export function generateCheckoutUrl(config: CheckoutConfig): string {
  const { productId, variantId, customData, discountCode } = config;
  
  // Validate required parameters
  if (!productId || typeof productId !== 'string' || productId.trim() === '') {
    throw new Error('Product ID is required and must be a non-empty string');
  }
  
  try {
    // Get the app URL from environment variables
    const appUrl = process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000';
    
    // Get the Lemon Squeezy store URL from environment variables
    // Default to the custom store domain if not set
    const storeUrl = process.env.NEXT_PUBLIC_LEMON_SQUEEZY_STORE_URL || 'https://digiinstastore.lemonsqueezy.com';
    
    // Build URL with product ID
    const url = new URL(`${storeUrl}/checkout/buy/${productId}`);
    
    // Add variant ID if provided
    if (variantId) {
      url.searchParams.set('variant', variantId);
    }
    
    // Add discount code if provided
    if (discountCode) {
      url.searchParams.set('discount', discountCode);
    }
    
    // Configure redirect URLs for post-purchase flow
    url.searchParams.set('checkout[success_url]', `${appUrl}/thank-you`);
    
    // Add custom data for tracking if provided
    if (customData) {
      Object.entries(customData).forEach(([key, value]) => {
        url.searchParams.set(`checkout[custom][${key}]`, String(value));
      });
    }
    
    // Enable checkout overlay mode
    url.searchParams.set('embed', '1');
    
    return url.toString();
  } catch (error) {
    console.error('Error generating checkout URL:', error);
    throw new Error('Failed to generate checkout URL. Please try again.');
  }
}

/**
 * Open the Lemon Squeezy checkout overlay
 * 
 * This function opens the checkout in an overlay/modal mode, providing
 * a seamless purchase experience without leaving the current page.
 * 
 * @param checkoutUrl - The checkout URL generated by generateCheckoutUrl
 * @throws Error if not in browser environment or if URL is invalid
 * 
 * @example
 * ```typescript
 * const checkoutUrl = generateCheckoutUrl({ productId: '123456' });
 * openCheckoutOverlay(checkoutUrl);
 * ```
 */
export function openCheckoutOverlay(checkoutUrl: string): void {
  // Check if we're in a browser environment
  if (typeof window === 'undefined') {
    const error = 'openCheckoutOverlay can only be called in browser environment';
    console.error(error);
    throw new Error(error);
  }
  
  // Validate checkout URL
  if (!checkoutUrl || typeof checkoutUrl !== 'string' || checkoutUrl.trim() === '') {
    throw new Error('Invalid checkout URL');
  }
  
  try {
    // Validate URL format
    new URL(checkoutUrl);
    
    // Open the checkout URL in the current window
    // The embed=1 parameter in the URL will trigger Lemon Squeezy's overlay mode
    window.location.href = checkoutUrl;
  } catch (error) {
    console.error('Error opening checkout overlay:', error);
    throw new Error('Failed to open checkout. Please try again.');
  }
}

/**
 * Create a checkout button event handler
 * 
 * This is a convenience function that combines URL generation and overlay opening
 * into a single handler suitable for button onClick events.
 * 
 * @param config - Checkout configuration
 * @returns Event handler function
 * @throws Error if checkout fails
 * 
 * @example
 * ```typescript
 * <button onClick={createCheckoutHandler({ productId: '123456' })}>
 *   Buy Now
 * </button>
 * ```
 */
export function createCheckoutHandler(config: CheckoutConfig) {
  return (event?: React.MouseEvent) => {
    // Prevent default link behavior if this is attached to an anchor
    event?.preventDefault();
    
    try {
      const checkoutUrl = generateCheckoutUrl(config);
      openCheckoutOverlay(checkoutUrl);
    } catch (error) {
      console.error('Checkout handler error:', error);
      throw error;
    }
  };
}
